import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./providers/ReduxProvider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Load Google Translate */}
      <Script
        src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"
        strategy="afterInteractive"
      />

      {/* Init function for Google Translate */}
      <Script id="google-translate-init" strategy="afterInteractive">
        {`
            window.googleTranslateElementInit = function () {
              new window.google.translate.TranslateElement({
                pageLanguage: 'de',            // GERMAN IS DEFAULT
                includedLanguages: 'de,en',   // German + English
                autoDisplay: false
              }, 'google_translate_element');
            };
          `}
      </Script>


      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Hidden div for Google widget */}
        <div id="google_translate_element" style={{ display: "none" }} />
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
